import CompleteReminder from "./CompleteReminder";
import Link from "next/link";
import { ArrowUpRight, ClipboardCheck, Inbox, BookOpen, Bell, ArrowRight } from "lucide-react";
import { getAdminOverview } from "@/lib/admin-overview";
import { adminStatusLabel } from "@/lib/admin-navigation";
import { formatKST } from "@/lib/formatKST";

export default async function AdminDashboard({ name }: { name: string }) {
  const data = await getAdminOverview();
  const today = formatKST(new Date(), "yyyy-MM-dd");
  const cards = [
    { label: "Pending applications", count: data.pending, href: "/dashboard/applications-admin?status=PENDING", icon: ClipboardCheck },
    { label: "New inquiries", count: data.inquiries, href: "/dashboard/leads?status=NEW", icon: Inbox },
    { label: "Published programs", count: data.published, href: "/dashboard/programs", icon: BookOpen },
  ];
  return <div className="space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-slate-500">Workspace</p><h1 className="text-3xl font-bold tracking-tight">Overview</h1><p className="mt-2 text-sm text-slate-500">Welcome, {name}. Review applications, follow up on inquiries and keep programs up to date.</p></div><span className="text-xs text-slate-500">{formatKST(new Date(), "MMM d, yyyy")} · Korea time</span></header>
    <div className="grid gap-4 sm:grid-cols-3">{cards.map(card => <Link key={card.label} href={card.href} prefetch={false} className="rounded-2xl border border-slate-200 bg-white p-5 transition-colors hover:border-blue-300"><div className="flex justify-between text-slate-500"><card.icon aria-hidden="true" size={20} /><ArrowUpRight aria-hidden="true" size={16} /></div><p className="mt-4 text-3xl font-bold tabular-nums">{card.count}</p><p className="mt-1 text-sm text-slate-600">{card.label}</p></Link>)}</div>
    {(data.overduePayments.length > 0 || data.interviews.length > 0) && <section className="rounded-2xl border border-amber-200 bg-amber-50/40 p-5"><h2 className="font-semibold">Needs attention</h2><p className="mt-1 text-xs text-slate-500">Up to six overdue payment follow-ups and six interviews in the next 24 hours.</p><ul className="mt-3 grid gap-3 md:grid-cols-2">{data.overduePayments.map(app => <li key={app.id}><Link prefetch={false} href={`/dashboard/users/${app.user.id}`} className="block rounded-xl border border-amber-100 bg-white p-3 text-sm"><strong>{app.user.name || app.user.email}</strong><p className="mt-1 text-amber-800">Payment follow-up overdue · {app.paymentDeadline && formatKST(app.paymentDeadline, "MMM d")}</p><p className="mt-1 text-xs text-slate-500">{app.program.title}</p></Link></li>)}{data.interviews.map(app => <li key={app.id}><Link prefetch={false} href={`/dashboard/users/${app.user.id}`} className="block rounded-xl border border-slate-200 bg-white p-3 text-sm"><strong>{app.user.name || app.user.email}</strong><p className="mt-1 text-blue-700">Interview · {app.interviewDate && formatKST(app.interviewDate, "MMM d, h:mm a")} KST</p><p className="mt-1 text-xs text-slate-500">{app.program.title}</p></Link></li>)}</ul></section>}
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(280px,1fr)]">
      <div className="space-y-6">
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><h2 className="font-semibold">Recent applications</h2><Link href="/dashboard/applications-admin" prefetch={false} className="inline-flex items-center gap-1 text-sm font-medium text-blue-700">View applications<ArrowRight aria-hidden="true" size={14} /></Link></div>
          {data.applications.length === 0 ? <p className="p-8 text-sm text-slate-500">No applications yet. New submissions will appear here.</p> : <ul className="divide-y divide-slate-100">{data.applications.map(app => <li key={app.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-2"><Link href={`/dashboard/users/${app.user.id}`} prefetch={false} className="font-semibold hover:text-blue-700">{app.user.name || app.user.email}</Link><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${app.status === "PENDING" ? "bg-amber-50 text-amber-800" : app.status === "ACCEPTED" ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{adminStatusLabel(app.status)}</span></div><p className="mt-1 text-sm text-slate-600">{app.program.title}</p><p className="mt-2 text-xs text-slate-400">{formatKST(app.createdAt, "MMM d, yyyy")}</p></li>)}</ul>}
        </section>
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex justify-between gap-3 border-b border-slate-100 p-5"><h2 className="font-semibold">Inquiry activity</h2><Link href="/dashboard/leads" prefetch={false} className="text-sm font-medium text-blue-700">View inquiries</Link></div>{data.activity.length === 0 ? <p className="p-8 text-sm text-slate-500">No inquiry activity yet.</p> : <ul className="divide-y divide-slate-100">{data.activity.map(log => <li key={log.id} className="p-5"><div className="flex flex-wrap justify-between gap-2"><Link href={`/dashboard/leads/${log.leadId}`} prefetch={false} className="text-sm font-semibold hover:text-blue-700">{log.lead.name}</Link><span className="text-xs text-slate-400">{formatKST(log.createdAt,"MMM d, h:mm a")}</span></div><p className="mt-2 line-clamp-2 break-words text-sm text-slate-600">{log.content}</p><p className="mt-2 text-xs text-slate-400">{log.adminName} · {adminStatusLabel(log.action)}</p></li>)}</ul>}</section>
      </div>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="flex items-center gap-2 font-semibold"><Bell aria-hidden="true" size={18} />Follow-up reminders<span className="ml-auto rounded-full bg-slate-100 px-2 py-0.5 text-xs">{data.reminders}</span></h2><p className="mt-2 text-xs text-slate-500">Unread reminders, earliest first. Includes overdue items.{data.reminders > 20 ? " Showing the first 20; open a person's record to manage their reminders." : ""}</p></div>{data.followups.length === 0 ? <p className="p-8 text-sm text-slate-500">You’re all caught up. No unread reminders.</p> : <ul className="max-h-[680px] divide-y divide-slate-100 overflow-y-auto">{data.followups.map(item => {
        const day = formatKST(item.dueDate, "yyyy-MM-dd");
        const href = item.leadId ? `/dashboard/leads/${item.leadId}` : item.userId ? `/dashboard/users/${item.userId}` : "/dashboard/leads";
        return <li key={item.id}><Link href={href} prefetch={false} className="block p-5 hover:bg-slate-50"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-semibold">{item.lead?.name || item.user?.name || item.user?.email || "Follow-up"}</span><span className={`text-xs font-semibold ${day < today ? "text-rose-700" : day === today ? "text-amber-700" : "text-slate-500"}`}>{day < today ? "Overdue" : day === today ? "Today" : formatKST(item.dueDate, "MMM d")}</span></div><p className="mt-2 break-words text-sm text-slate-600">{item.message}</p><p className="mt-2 text-xs text-slate-400">{formatKST(item.dueDate, "MMM d, h:mm a")} KST</p></Link><div className="px-5 pb-4"><CompleteReminder id={item.id} /></div></li>;
      })}</ul>}</section>
    </div>
  </div>;
}
